/*
 * Copyright 1999-2018 Alibaba Group Holding Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/******************************************/
/*   数据库全名 = nacos   */
/*   表名称 = config_info   */
/******************************************/

create user "NACOS" identified by "Aa12345678!" DEFAULT TABLESPACE IPA_DB DEFAULT INDEX TABLESPACE IPA_INDEX;
grant "DBA","PUBLIC" to "NACOS";

CREATE TABLE "NACOS"."USERS"
(
 "USERNAME" VARCHAR(50) NOT NULL,
 "PASSWORD" VARCHAR(500) NOT NULL,
 "ENABLED" TINYINT NOT NULL
);

CREATE TABLE "NACOS"."TENANT_INFO"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "KP" VARCHAR(128) NOT NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NULL,
 "TENANT_NAME" VARCHAR(128) DEFAULT ''
 NULL,
 "TENANT_DESC" VARCHAR(256) NULL,
 "CREATE_SOURCE" VARCHAR(32) NULL,
 "GMT_CREATE" BIGINT NOT NULL,
 "GMT_MODIFIED" BIGINT NOT NULL
);

CREATE TABLE "NACOS"."TENANT_CAPACITY"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NOT NULL,
 "QUOTA" BIGINT DEFAULT 0
 NOT NULL,
 "USAGE" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_SIZE" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_AGGR_COUNT" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_AGGR_SIZE" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_HISTORY_COUNT" BIGINT DEFAULT 0
 NOT NULL,
 "GMT_CREATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "GMT_MODIFIED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

CREATE TABLE "NACOS"."ROLES"
(
 "USERNAME" VARCHAR(50) NOT NULL,
 "ROLE" VARCHAR(50) NOT NULL
);

CREATE TABLE "NACOS"."PERMISSIONS"
(
 "ROLE" VARCHAR(50) NOT NULL,
 "RESOURCE" VARCHAR(255) NOT NULL,
 "ACTION" VARCHAR(8) NOT NULL
);

CREATE TABLE "NACOS"."HIS_CONFIG_INFO"
(
 "ID" BIGINT NOT NULL,
 "NID" BIGINT IDENTITY(332,1) NOT NULL,
 "DATA_ID" VARCHAR(255) NOT NULL,
 "GROUP_ID" VARCHAR(128) NOT NULL,
 "APP_NAME" VARCHAR(128) NULL,
 "CONTENT" CLOB NOT NULL,
 "MD5" VARCHAR(32) NULL,
 "GMT_CREATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "GMT_MODIFIED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "SRC_USER" TEXT NULL,
 "SRC_IP" VARCHAR(20) NULL,
 "OP_TYPE" CHAR(10) NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NULL
);

CREATE TABLE "NACOS"."GROUP_CAPACITY"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "GROUP_ID" VARCHAR(128) DEFAULT ''
 NOT NULL,
 "QUOTA" BIGINT DEFAULT 0
 NOT NULL,
 "USAGE" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_SIZE" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_AGGR_COUNT" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_AGGR_SIZE" BIGINT DEFAULT 0
 NOT NULL,
 "MAX_HISTORY_COUNT" BIGINT DEFAULT 0
 NOT NULL,
 "GMT_CREATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "GMT_MODIFIED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL
);

CREATE TABLE "NACOS"."CONFIG_TAGS_RELATION"
(
 "ID" BIGINT NOT NULL,
 "TAG_NAME" VARCHAR(128) NOT NULL,
 "TAG_TYPE" VARCHAR(64) NULL,
 "DATA_ID" VARCHAR(255) NOT NULL,
 "GROUP_ID" VARCHAR(128) NOT NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NULL,
 "NID" BIGINT IDENTITY(2,1) NOT NULL
);

CREATE TABLE "NACOS"."CONFIG_INFO_TAG"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "DATA_ID" VARCHAR(255) NOT NULL,
 "GROUP_ID" VARCHAR(128) NOT NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NULL,
 "TAG_ID" VARCHAR(128) NOT NULL,
 "APP_NAME" VARCHAR(128) NULL,
 "CONTENT" CLOB NOT NULL,
 "MD5" VARCHAR(32) NULL,
 "GMT_CREATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "GMT_MODIFIED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "SRC_USER" TEXT NULL,
 "SRC_IP" VARCHAR(20) NULL
);

CREATE TABLE "NACOS"."CONFIG_INFO_BETA"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "DATA_ID" VARCHAR(255) NOT NULL,
 "GROUP_ID" VARCHAR(128) NOT NULL,
 "APP_NAME" VARCHAR(128) NULL,
 "CONTENT" CLOB NOT NULL,
 "BETA_IPS" VARCHAR(1024) NULL,
 "MD5" VARCHAR(32) NULL,
 "GMT_CREATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "GMT_MODIFIED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "SRC_USER" TEXT NULL,
 "SRC_IP" VARCHAR(20) NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NULL
);

CREATE TABLE "NACOS"."CONFIG_INFO_AGGR"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "DATA_ID" VARCHAR(255) NOT NULL,
 "GROUP_ID" VARCHAR(255) NOT NULL,
 "DATUM_ID" VARCHAR(255) NOT NULL,
 "CONTENT" CLOB NOT NULL,
 "GMT_MODIFIED" TIMESTAMP(0) NOT NULL,
 "APP_NAME" VARCHAR(128) NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NULL
);

CREATE TABLE "NACOS"."CONFIG_INFO"
(
 "ID" BIGINT IDENTITY(305,1) NOT NULL,
 "DATA_ID" VARCHAR(255) NOT NULL,
 "GROUP_ID" VARCHAR(255) NULL,
 "CONTENT" CLOB NOT NULL,
 "MD5" VARCHAR(32) NULL,
 "GMT_CREATE" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "GMT_MODIFIED" TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP()
 NOT NULL,
 "SRC_USER" TEXT NULL,
 "SRC_IP" VARCHAR(20) NULL,
 "APP_NAME" VARCHAR(128) NULL,
 "TENANT_ID" VARCHAR(128) DEFAULT ''
 NULL,
 "C_DESC" VARCHAR(256) NULL,
 "C_USE" VARCHAR(64) NULL,
 "EFFECT" VARCHAR(64) NULL,
 "TYPE" VARCHAR(64) NULL,
 "C_SCHEMA" TEXT NULL
);

ALTER TABLE "NACOS"."USERS" ADD CONSTRAINT  PRIMARY KEY("USERNAME") ;

ALTER TABLE "NACOS"."TENANT_INFO" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "NACOS"."TENANT_INFO" ADD CONSTRAINT "UK_TENANT_INFO_KPTENANTID" UNIQUE("KP","TENANT_ID") ;

ALTER TABLE "NACOS"."ROLES" ADD CONSTRAINT "IDX_USER_ROLE" UNIQUE("USERNAME","ROLE") ;

ALTER TABLE "NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT  PRIMARY KEY("NID") ;

ALTER TABLE "NACOS"."CONFIG_TAGS_RELATION" ADD CONSTRAINT "UK_CONFIGTAGRELATION_CONFIGIDTAG" UNIQUE("ID","TAG_NAME","TAG_TYPE") ;

ALTER TABLE "NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "NACOS"."CONFIG_INFO_TAG" ADD CONSTRAINT "UK_CONFIGINFOTAG_DATAGROUPTENANTTAG" UNIQUE("DATA_ID","GROUP_ID","TENANT_ID","TAG_ID") ;

ALTER TABLE "NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "NACOS"."CONFIG_INFO_BETA" ADD CONSTRAINT "UK_CONFIGINFOBETA_DATAGROUPTENANT" UNIQUE("DATA_ID","GROUP_ID","TENANT_ID") ;

ALTER TABLE "NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "NACOS"."CONFIG_INFO_AGGR" ADD CONSTRAINT "UK_CONFIGINFOAGGR_DATAGROUPTENANTDATUM" UNIQUE("DATA_ID","GROUP_ID","TENANT_ID","DATUM_ID") ;

ALTER TABLE "NACOS"."CONFIG_INFO" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "NACOS"."CONFIG_INFO" ADD CONSTRAINT "UK_CONFIGINFO_DATAGROUPTENANT" UNIQUE("DATA_ID","GROUP_ID","TENANT_ID") ;

CREATE UNIQUE INDEX "PRIMARY"
ON "NACOS"."USERS"("USERNAME");

CREATE INDEX "IDX_TENANT_ID"
ON "NACOS"."TENANT_INFO"("TENANT_ID");

CREATE UNIQUE INDEX "INDEX26297553086800"
ON "NACOS"."TENANT_INFO"("ID");

COMMENT ON TABLE "NACOS"."TENANT_INFO" IS 'tenant_info';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."ID" IS 'id';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."KP" IS 'kp';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."TENANT_ID" IS 'tenant_id';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."TENANT_NAME" IS 'tenant_name';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."TENANT_DESC" IS 'tenant_desc';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."CREATE_SOURCE" IS 'create_source';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."GMT_CREATE" IS '创建时间';

COMMENT ON COLUMN "NACOS"."TENANT_INFO"."GMT_MODIFIED" IS '修改时间';

CREATE INDEX "UK_ROLE_PERMISSION"
ON "NACOS"."PERMISSIONS"("ROLE");

CREATE INDEX "INDEX26298171206400"
ON "NACOS"."CONFIG_TAGS_RELATION"("TENANT_ID");

CREATE UNIQUE INDEX "INDEX26298293911500"
ON "NACOS"."CONFIG_TAGS_RELATION"("NID");

COMMENT ON TABLE "NACOS"."CONFIG_TAGS_RELATION" IS 'config_tag_relation';

COMMENT ON COLUMN "NACOS"."CONFIG_TAGS_RELATION"."ID" IS 'id';

COMMENT ON COLUMN "NACOS"."CONFIG_TAGS_RELATION"."TAG_NAME" IS 'tag_name';

COMMENT ON COLUMN "NACOS"."CONFIG_TAGS_RELATION"."TAG_TYPE" IS 'tag_type';

COMMENT ON COLUMN "NACOS"."CONFIG_TAGS_RELATION"."DATA_ID" IS 'data_id';

COMMENT ON COLUMN "NACOS"."CONFIG_TAGS_RELATION"."GROUP_ID" IS 'group_id';

COMMENT ON COLUMN "NACOS"."CONFIG_TAGS_RELATION"."TENANT_ID" IS 'tenant_id';

CREATE UNIQUE INDEX "INDEX26298757325300"
ON "NACOS"."CONFIG_INFO_TAG"("ID");

COMMENT ON TABLE "NACOS"."CONFIG_INFO_TAG" IS 'config_info_tag';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."ID" IS 'id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."DATA_ID" IS 'data_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."GROUP_ID" IS 'group_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."TENANT_ID" IS 'tenant_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."TAG_ID" IS 'tag_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."APP_NAME" IS 'app_name';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."CONTENT" IS 'content';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."MD5" IS 'md5';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."GMT_CREATE" IS '创建时间';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."GMT_MODIFIED" IS '修改时间';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."SRC_USER" IS 'source user';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_TAG"."SRC_IP" IS 'source ip';

CREATE UNIQUE INDEX "INDEX26299674328600"
ON "NACOS"."CONFIG_INFO_BETA"("ID");

COMMENT ON TABLE "NACOS"."CONFIG_INFO_BETA" IS 'config_info_beta';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."ID" IS 'id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."DATA_ID" IS 'data_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."GROUP_ID" IS 'group_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."APP_NAME" IS 'app_name';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."CONTENT" IS 'content';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."BETA_IPS" IS 'betaIps';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."MD5" IS 'md5';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."GMT_CREATE" IS '创建时间';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."GMT_MODIFIED" IS '修改时间';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."SRC_USER" IS 'source user';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."SRC_IP" IS 'source ip';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_BETA"."TENANT_ID" IS '租户字段';

CREATE UNIQUE INDEX "INDEX26300779384000"
ON "NACOS"."CONFIG_INFO_AGGR"("ID");

COMMENT ON TABLE "NACOS"."CONFIG_INFO_AGGR" IS '增加租户字段';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_AGGR"."ID" IS 'id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_AGGR"."DATA_ID" IS 'data_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_AGGR"."GROUP_ID" IS 'group_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_AGGR"."DATUM_ID" IS 'datum_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_AGGR"."CONTENT" IS '内容';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_AGGR"."GMT_MODIFIED" IS '修改时间';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO_AGGR"."TENANT_ID" IS '租户字段';

CREATE UNIQUE INDEX "INDEX26301501831500"
ON "NACOS"."CONFIG_INFO"("ID");

COMMENT ON TABLE "NACOS"."CONFIG_INFO" IS 'config_info';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."ID" IS 'id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."DATA_ID" IS 'data_id';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."CONTENT" IS 'content';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."MD5" IS 'md5';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."GMT_CREATE" IS '创建时间';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."GMT_MODIFIED" IS '修改时间';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."SRC_USER" IS 'source user';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."SRC_IP" IS 'source ip';

COMMENT ON COLUMN "NACOS"."CONFIG_INFO"."TENANT_ID" IS '租户字段';


INSERT INTO nacos.users (username, password, enabled) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', TRUE);

INSERT INTO nacos.roles (username, role) VALUES ('nacos', 'ROLE_ADMIN');
